version: '3.1'

services:
  db:
    image: postgres:11
    container_name: teknix-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: teknix-express
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    restart: 'always'